### ISSUE TITLE
Include NuGet reference for Microsoft.IdentityModel

### ISSUE THREAD

**Issue by johnnycardy** [s-KaiNet/SharePoint-AspNet-Authentication#2]
At the moment, the Microsoft.IdentityModel assembly is pulled from the GAC, resulting in this error when the project is deployed:

Could not load file or assembly 'Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Here is the nuget package that should be added:
https://www.nuget.org/packages/Microsoft.IdentityModel/

**Comment by s-KaiNet** [comment]
Thanks Jonathan, added required module in dependencies.
